"""Simplified PKs again

Revision ID: 56e3caba59d0
Revises: 
Create Date: 2025-06-20 07:48:30.910432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e3caba59d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkinglots_details',
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.Column('parking_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('parkinglot_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_phone_no', sa.String(length=15), nullable=False),
    sa.Column('user_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_phone_no')
    )
    op.create_table('floors',
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=50), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parkinglot_id'], ['parkinglots_details.parkinglot_id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_table('rows',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('row_name', sa.String(length=50), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.floor_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg_no', sa.String(length=20), nullable=True),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['rows.row_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('parking_sessions',
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('parkinglot_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg_no', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_sessions')
    op.drop_table('slots')
    op.drop_table('rows')
    op.drop_table('floors')
    op.drop_table('users')
    op.drop_table('parkinglots_details')
    # ### end Alembic commands ###
